# Generated by Django 5.1.7 on 2025-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'NEBULOSA'), ('Estrela', 'ESTRELA'), ('Planeta', 'PLANETA'), ('Galáxia', 'GALÁXIA')], default='', max_length=100),
        ),
    ]
